//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BeautyShopEntities1 : DbContext
    {
        public BeautyShopEntities1()
            : base("name=BeautyShopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Work> Work { get; set; }
    
        public virtual int Clients_AUTO_GENERATION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Clients_AUTO_GENERATION");
        }
    
        public virtual int Clients_DELETE(Nullable<int> key)
        {
            var keyParameter = key.HasValue ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Clients_DELETE", keyParameter);
        }
    
        public virtual int Clients_INSERT(string inSurname, string inName, string inMiddle, Nullable<System.DateTime> inBirhdate, string inEmail, Nullable<decimal> inPhone, string inComment)
        {
            var inSurnameParameter = inSurname != null ?
                new ObjectParameter("inSurname", inSurname) :
                new ObjectParameter("inSurname", typeof(string));
    
            var inNameParameter = inName != null ?
                new ObjectParameter("inName", inName) :
                new ObjectParameter("inName", typeof(string));
    
            var inMiddleParameter = inMiddle != null ?
                new ObjectParameter("inMiddle", inMiddle) :
                new ObjectParameter("inMiddle", typeof(string));
    
            var inBirhdateParameter = inBirhdate.HasValue ?
                new ObjectParameter("inBirhdate", inBirhdate) :
                new ObjectParameter("inBirhdate", typeof(System.DateTime));
    
            var inEmailParameter = inEmail != null ?
                new ObjectParameter("inEmail", inEmail) :
                new ObjectParameter("inEmail", typeof(string));
    
            var inPhoneParameter = inPhone.HasValue ?
                new ObjectParameter("inPhone", inPhone) :
                new ObjectParameter("inPhone", typeof(decimal));
    
            var inCommentParameter = inComment != null ?
                new ObjectParameter("inComment", inComment) :
                new ObjectParameter("inComment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Clients_INSERT", inSurnameParameter, inNameParameter, inMiddleParameter, inBirhdateParameter, inEmailParameter, inPhoneParameter, inCommentParameter);
        }
    
        public virtual ObjectResult<Clients_SELECT_Result> Clients_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Clients_SELECT_Result>("Clients_SELECT");
        }
    
        public virtual int Clients_UPDATE(Nullable<int> inId, string inSurname, string inName, string inMiddle, Nullable<System.DateTime> inBirhdate, string inEmail, Nullable<decimal> inPhone, string inComment)
        {
            var inIdParameter = inId.HasValue ?
                new ObjectParameter("inId", inId) :
                new ObjectParameter("inId", typeof(int));
    
            var inSurnameParameter = inSurname != null ?
                new ObjectParameter("inSurname", inSurname) :
                new ObjectParameter("inSurname", typeof(string));
    
            var inNameParameter = inName != null ?
                new ObjectParameter("inName", inName) :
                new ObjectParameter("inName", typeof(string));
    
            var inMiddleParameter = inMiddle != null ?
                new ObjectParameter("inMiddle", inMiddle) :
                new ObjectParameter("inMiddle", typeof(string));
    
            var inBirhdateParameter = inBirhdate.HasValue ?
                new ObjectParameter("inBirhdate", inBirhdate) :
                new ObjectParameter("inBirhdate", typeof(System.DateTime));
    
            var inEmailParameter = inEmail != null ?
                new ObjectParameter("inEmail", inEmail) :
                new ObjectParameter("inEmail", typeof(string));
    
            var inPhoneParameter = inPhone.HasValue ?
                new ObjectParameter("inPhone", inPhone) :
                new ObjectParameter("inPhone", typeof(decimal));
    
            var inCommentParameter = inComment != null ?
                new ObjectParameter("inComment", inComment) :
                new ObjectParameter("inComment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Clients_UPDATE", inIdParameter, inSurnameParameter, inNameParameter, inMiddleParameter, inBirhdateParameter, inEmailParameter, inPhoneParameter, inCommentParameter);
        }
    
        public virtual int Employee_AUTO_GENERATION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Employee_AUTO_GENERATION");
        }
    
        public virtual int Employee_DELETE(Nullable<int> key)
        {
            var keyParameter = key.HasValue ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Employee_DELETE", keyParameter);
        }
    
        public virtual int Employee_INSERT(string inSurname, string inName, string inMiddle, Nullable<decimal> inPhone, Nullable<System.DateTime> inBirhdate, string inPost, string inComment)
        {
            var inSurnameParameter = inSurname != null ?
                new ObjectParameter("inSurname", inSurname) :
                new ObjectParameter("inSurname", typeof(string));
    
            var inNameParameter = inName != null ?
                new ObjectParameter("inName", inName) :
                new ObjectParameter("inName", typeof(string));
    
            var inMiddleParameter = inMiddle != null ?
                new ObjectParameter("inMiddle", inMiddle) :
                new ObjectParameter("inMiddle", typeof(string));
    
            var inPhoneParameter = inPhone.HasValue ?
                new ObjectParameter("inPhone", inPhone) :
                new ObjectParameter("inPhone", typeof(decimal));
    
            var inBirhdateParameter = inBirhdate.HasValue ?
                new ObjectParameter("inBirhdate", inBirhdate) :
                new ObjectParameter("inBirhdate", typeof(System.DateTime));
    
            var inPostParameter = inPost != null ?
                new ObjectParameter("inPost", inPost) :
                new ObjectParameter("inPost", typeof(string));
    
            var inCommentParameter = inComment != null ?
                new ObjectParameter("inComment", inComment) :
                new ObjectParameter("inComment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Employee_INSERT", inSurnameParameter, inNameParameter, inMiddleParameter, inPhoneParameter, inBirhdateParameter, inPostParameter, inCommentParameter);
        }
    
        public virtual ObjectResult<Employee_SELECT_Result> Employee_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Employee_SELECT_Result>("Employee_SELECT");
        }
    
        public virtual int Employee_UPDATE(Nullable<int> inId, string inSurname, string inName, string inMiddle, Nullable<System.DateTime> inBirhdate, string inPost, Nullable<decimal> inPhone, string inComment)
        {
            var inIdParameter = inId.HasValue ?
                new ObjectParameter("inId", inId) :
                new ObjectParameter("inId", typeof(int));
    
            var inSurnameParameter = inSurname != null ?
                new ObjectParameter("inSurname", inSurname) :
                new ObjectParameter("inSurname", typeof(string));
    
            var inNameParameter = inName != null ?
                new ObjectParameter("inName", inName) :
                new ObjectParameter("inName", typeof(string));
    
            var inMiddleParameter = inMiddle != null ?
                new ObjectParameter("inMiddle", inMiddle) :
                new ObjectParameter("inMiddle", typeof(string));
    
            var inBirhdateParameter = inBirhdate.HasValue ?
                new ObjectParameter("inBirhdate", inBirhdate) :
                new ObjectParameter("inBirhdate", typeof(System.DateTime));
    
            var inPostParameter = inPost != null ?
                new ObjectParameter("inPost", inPost) :
                new ObjectParameter("inPost", typeof(string));
    
            var inPhoneParameter = inPhone.HasValue ?
                new ObjectParameter("inPhone", inPhone) :
                new ObjectParameter("inPhone", typeof(decimal));
    
            var inCommentParameter = inComment != null ?
                new ObjectParameter("inComment", inComment) :
                new ObjectParameter("inComment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Employee_UPDATE", inIdParameter, inSurnameParameter, inNameParameter, inMiddleParameter, inBirhdateParameter, inPostParameter, inPhoneParameter, inCommentParameter);
        }
    
        public virtual int Generation_Email(ObjectParameter resultEmail)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Generation_Email", resultEmail);
        }
    
        public virtual ObjectResult<Record_AUTO_GENERATION_Result> Record_AUTO_GENERATION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Record_AUTO_GENERATION_Result>("Record_AUTO_GENERATION");
        }
    
        public virtual int Record_DELETE(Nullable<int> key)
        {
            var keyParameter = key.HasValue ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Record_DELETE", keyParameter);
        }
    
        public virtual int Record_INSERT(Nullable<int> id_services, Nullable<int> id_Employee, Nullable<int> id_Clients, Nullable<System.DateTime> date, Nullable<System.TimeSpan> time, string comment)
        {
            var id_servicesParameter = id_services.HasValue ?
                new ObjectParameter("Id_services", id_services) :
                new ObjectParameter("Id_services", typeof(int));
    
            var id_EmployeeParameter = id_Employee.HasValue ?
                new ObjectParameter("Id_Employee", id_Employee) :
                new ObjectParameter("Id_Employee", typeof(int));
    
            var id_ClientsParameter = id_Clients.HasValue ?
                new ObjectParameter("Id_Clients", id_Clients) :
                new ObjectParameter("Id_Clients", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var timeParameter = time.HasValue ?
                new ObjectParameter("Time", time) :
                new ObjectParameter("Time", typeof(System.TimeSpan));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Record_INSERT", id_servicesParameter, id_EmployeeParameter, id_ClientsParameter, dateParameter, timeParameter, commentParameter);
        }
    
        public virtual ObjectResult<Record_SELECT_Result> Record_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Record_SELECT_Result>("Record_SELECT");
        }
    
        public virtual int Record_UPDATE(Nullable<int> id, Nullable<int> id_services, Nullable<int> id_Employee, Nullable<int> id_Clients, Nullable<System.DateTime> date, Nullable<System.TimeSpan> time, string comment)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var id_servicesParameter = id_services.HasValue ?
                new ObjectParameter("Id_services", id_services) :
                new ObjectParameter("Id_services", typeof(int));
    
            var id_EmployeeParameter = id_Employee.HasValue ?
                new ObjectParameter("Id_Employee", id_Employee) :
                new ObjectParameter("Id_Employee", typeof(int));
    
            var id_ClientsParameter = id_Clients.HasValue ?
                new ObjectParameter("Id_Clients", id_Clients) :
                new ObjectParameter("Id_Clients", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var timeParameter = time.HasValue ?
                new ObjectParameter("Time", time) :
                new ObjectParameter("Time", typeof(System.TimeSpan));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Record_UPDATE", idParameter, id_servicesParameter, id_EmployeeParameter, id_ClientsParameter, dateParameter, timeParameter, commentParameter);
        }
    
        public virtual int Services_DELETE(Nullable<int> key)
        {
            var keyParameter = key.HasValue ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Services_DELETE", keyParameter);
        }
    
        public virtual int Services_INSERT(string name, string comment, Nullable<int> price)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Services_INSERT", nameParameter, commentParameter, priceParameter);
        }
    
        public virtual ObjectResult<Services_SELECT_Result> Services_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Services_SELECT_Result>("Services_SELECT");
        }
    
        public virtual int Services_UPDATE(Nullable<int> id, string name, string comment, Nullable<int> price)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Services_UPDATE", idParameter, nameParameter, commentParameter, priceParameter);
        }
    
        public virtual ObjectResult<SP1_Result> SP1(Nullable<System.DateTime> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP1_Result>("SP1", yearParameter);
        }
    
        public virtual ObjectResult<SP2_Result> SP2(string letter)
        {
            var letterParameter = letter != null ?
                new ObjectParameter("letter", letter) :
                new ObjectParameter("letter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP2_Result>("SP2", letterParameter);
        }
    
        public virtual ObjectResult<Work_AUTO_GENERATION_Result> Work_AUTO_GENERATION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Work_AUTO_GENERATION_Result>("Work_AUTO_GENERATION");
        }
    
        public virtual int Work_DELETE(Nullable<int> key)
        {
            var keyParameter = key.HasValue ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Work_DELETE", keyParameter);
        }
    
        public virtual int Work_INSERT(Nullable<int> id_services, Nullable<int> id_Employee, Nullable<int> id_Clients, Nullable<System.DateTime> date, Nullable<System.TimeSpan> time, Nullable<double> income, string comment)
        {
            var id_servicesParameter = id_services.HasValue ?
                new ObjectParameter("Id_services", id_services) :
                new ObjectParameter("Id_services", typeof(int));
    
            var id_EmployeeParameter = id_Employee.HasValue ?
                new ObjectParameter("Id_Employee", id_Employee) :
                new ObjectParameter("Id_Employee", typeof(int));
    
            var id_ClientsParameter = id_Clients.HasValue ?
                new ObjectParameter("Id_Clients", id_Clients) :
                new ObjectParameter("Id_Clients", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var timeParameter = time.HasValue ?
                new ObjectParameter("Time", time) :
                new ObjectParameter("Time", typeof(System.TimeSpan));
    
            var incomeParameter = income.HasValue ?
                new ObjectParameter("Income", income) :
                new ObjectParameter("Income", typeof(double));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Work_INSERT", id_servicesParameter, id_EmployeeParameter, id_ClientsParameter, dateParameter, timeParameter, incomeParameter, commentParameter);
        }
    
        public virtual ObjectResult<Work_SELECT_Result> Work_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Work_SELECT_Result>("Work_SELECT");
        }
    
        public virtual int Work_UPDATE(Nullable<int> id, Nullable<int> id_services, Nullable<int> id_Employee, Nullable<int> id_Clients, Nullable<System.DateTime> date, Nullable<System.TimeSpan> time, Nullable<double> income, string comment)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var id_servicesParameter = id_services.HasValue ?
                new ObjectParameter("Id_services", id_services) :
                new ObjectParameter("Id_services", typeof(int));
    
            var id_EmployeeParameter = id_Employee.HasValue ?
                new ObjectParameter("Id_Employee", id_Employee) :
                new ObjectParameter("Id_Employee", typeof(int));
    
            var id_ClientsParameter = id_Clients.HasValue ?
                new ObjectParameter("Id_Clients", id_Clients) :
                new ObjectParameter("Id_Clients", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var timeParameter = time.HasValue ?
                new ObjectParameter("Time", time) :
                new ObjectParameter("Time", typeof(System.TimeSpan));
    
            var incomeParameter = income.HasValue ?
                new ObjectParameter("Income", income) :
                new ObjectParameter("Income", typeof(double));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Work_UPDATE", idParameter, id_servicesParameter, id_EmployeeParameter, id_ClientsParameter, dateParameter, timeParameter, incomeParameter, commentParameter);
        }
    }
}
